name: Auto-update Pre-commit
run-name: Updating Pre-commit Configuration on ${{ github.repository }}

on:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight UTC
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  auto_update:
    name: Perform auto-update of pre-commit configuration
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3b1c91e8873ae0c705b0709f957c7a6a5eaf10 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v3.5.3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v4.7.0
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install and upgrade PIP
        run: python -m pip install --upgrade pip

      - name: Install Pre-commit
        run: pip install pre-commit

      - name: Update pre-commit
        run: pre-commit autoupdate

      - name: Create PR
        uses: peter-evans/create-pull-request@8500972a1322d52aebd0e3050bc201599f71661f # v5.0.2
        with:
          token: ${{ secrets.SEYLUBOT_PAT }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          delete-branch: true
