name: Auto-approve PR
run-name: Checking if elegible for auto-approving PR

on: pull_request

jobs:
  auto-approve:
    name: Perform Auto-approve PR
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    if: github.event.pull_request.user.login == ${{ github.repository_owner }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f0db2aa8a570959027d6be2a227028ad19fd9e8f # v2.5.0
        with:
          egress-policy: audit

      - name: Auto-approve PR via seyLu Bot
        uses: hmarr/auto-approve-action@8f929096a962e83ccdfa8afcf855f39f12d4dac7 # v3.2.1
        with:
          github-token: ${{ secrets.SEYLUBOT_PAT }}
